vars:
  - ./config/endpoints.yaml

stages:
  preprocess_data:
    cmd: python scripts/01_preprocess_data.py
    deps:
      - scripts/01_preprocess_data.py
      - data/imported_data/toxcast_data.csv.gz
    outs:
      - data/intermediate_data/ml_ready_data.tsv
  assign_groups:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python scripts/02_assign_groups.py  --endpoint ${item}  --n_groups 5
      deps:
        - scripts/02_assign_groups.py
        - data/intermediate_data/ml_ready_data.tsv
      outs:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
  ml_experiments:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/03_ml_experiments.py --endpoint ${item}
      deps:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
        - ./scripts/03_ml_experiments.py
      outs:
        - ./data/intermediate_data/model_predictions/morgan_fingerprint_predictions_${item}.tsv.gz
  neural_fingerprint_predictions:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/04_neural_fingerprint_predictions.py  --endpoint ${item}
      deps:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
        - ./scripts/04_neural_fingerprint_predictions.py
      outs:
        - ./data/intermediate_data/model_predictions/neural_fingerprint_predictions_${item}.tsv.gz
  create_plots:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/04_create_plots.py --endpoint ${item}
      deps:
        - data/intermediate_data/model_predictions/morgan_fingerprint_predictions_${item}.tsv.gz
        - data/intermediate_data/model_predictions/neural_fingerprint_predictions_${item}.tsv.gz
        - ./scripts/05_create_plots.py
      outs:
        - ./data/figures/${item}/proba_distribution_rf.png
        - ./data/figures/${item}/calibration_curves.png
        - ./data/figures/${item}/performance_metrics.png
        - ./data/figures/${item}/similarity_to_training.png
        - ./data/figures/${item}/test_set_composition.png
  create_final_plots:
    cmd: python scripts/06_create_final_figures.py --endpoint_a "BSK_4H_Eotaxin3_down" --endpoint_b "ATG_PXRE_CIS_up"
    deps:
      - ./data/intermediate_data/model_predictions
      - ./scripts/06_create_final_figures.py
    outs:
      - ./data/figures/final_figures/proba_distribution_rf.png
      - ./data/figures/final_figures/calibration_curves.png
      - ./data/figures/final_figures/performance_metrics.png
      - ./data/figures/final_figures/performance_metrics_alt.png
      - ./data/figures/final_figures/similarity_to_training.png
      - ./data/figures/final_figures/test_set_composition.png
