vars:
  - ./config/endpoints.yaml

stages:
  assign_groups:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python scripts/01_assign_groups.py  --endpoint ${item}
      deps:
        - data/imported_data/ml_ready_data.tsv
        - scripts/01_assign_groups.py
      outs:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
  ml_experiments:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/02_ml_experiments.py --endpoint ${item}
      deps:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
        - ./scripts/02_ml_experiments.py
      outs:
        - ./data/intermediate_data/model_predictions/morgan_fingerprint_predictions_${item}.tsv.gz
  neural_fingerprint_predictions:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/03_neural_fingerprint_predictions.py  --endpoint ${item}
      deps:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
        - ./scripts/03_neural_fingerprint_predictions.py
      outs:
        - ./data/intermediate_data/model_predictions/neural_fingerprint_predictions_${item}.tsv.gz
