vars:
  - ./config/endpoints.yaml

stages:
  preprocess_data:
    cmd: python scripts/01_preprocess_data.py
    deps:
      - scripts/01_preprocess_data.py
      - data/imported_data/toxcast_data.csv.gz
    outs:
      - data/intermediate_data/ml_ready_data.tsv
      - logs/01_preprocess_data.log
  assign_groups:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python scripts/02_assign_groups.py  --endpoint ${item}  --n_groups 5
      deps:
        - scripts/02_assign_groups.py
        - data/intermediate_data/ml_ready_data.tsv
      outs:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
  ml_experiments:
    matrix:
      endpoint: ${endpoint}
      counted_fp: [not_counted, counted]
    cmd: python ./scripts/03_ml_experiments.py --endpoint ${item.endpoint} --counted_fp ${item.counted_fp}
    deps:
      - data/intermediate_data/presplit_data/presplit_data_${item.endpoint}.tsv
      - ./scripts/03_ml_experiments.py
    outs:
      - ./data/intermediate_data/model_predictions/morgan_fingerprint_predictions_${item.endpoint}_${item.counted_fp}.tsv.gz
  neural_fingerprint_predictions:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/04_neural_fingerprint_predictions.py  --endpoint ${item}
      deps:
        - data/intermediate_data/presplit_data/presplit_data_${item}.tsv
        - ./scripts/04_neural_fingerprint_predictions.py
      outs:
        - ./data/intermediate_data/model_predictions/neural_fingerprint_predictions_${item}.tsv.gz
  create_plots:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/05_create_plots.py --endpoint ${item}
      deps:
        - data/intermediate_data/model_predictions/morgan_fingerprint_predictions_${item}_not_counted.tsv.gz
        - data/intermediate_data/model_predictions/neural_fingerprint_predictions_${item}.tsv.gz
        - ./scripts/05_create_plots.py
      outs:
        - ./data/figures/${item}/proba_distribution_rf.png
        - ./data/figures/${item}/proba_distribution_chemprop.png
        - ./data/figures/${item}/calibration_curves.png
        - ./data/figures/${item}/performance_metrics.png
        - ./data/figures/${item}/data_report.png
  create_final_plots:
    cmd: python scripts/06_create_final_figures.py
    deps:
      - ./data/intermediate_data/model_predictions
      - ./scripts/06_create_final_figures.py
    outs:
      - ./data/figures/final_figures/performance_metrics_all.png
      - ./data/figures/final_figures/significance_plot.png
      - ./data/figures/final_figures/scatter_metrics.png
  create_final_tables:
    cmd: python scripts/07_create_final_tables.py
    deps:
      - ./data/intermediate_data/model_predictions
      - ./scripts/07_create_final_tables.py
    outs:
      - ./logs/07_create_final_tables.log
