vars:
  - ./config/endpoints.yaml

stages:
  assign_groups:
    cmd: python scripts/01_assign_groups.py
    deps:
      - data/imported_data/ml_ready_data.tsv
      - scripts/01_assign_groups.py
    outs:
      - data/intermediate_data/tox21_presplit.tsv
  ml_experiments:
    foreach: ${endpoint}  # Specified in data_config.yaml
    do:
      cmd: python ./scripts/02_ml_experiments.py --endpoint ${item}
      deps:
        - ./data/intermediate_data/tox21_presplit.tsv
        - ./scripts/02_ml_experiments.py
      outs:
        - ./data/intermediate_data/model_predictions/test_set_predictions_${item}.tsv.gz
