endpoint:
  - "APR_HepG2_CellLoss_72h_dn"
  - "ATG_NRF2_ARE_CIS_up"
  - "ATG_PXRE_CIS_up"
  - "BSK_3C_HLADR_down"
  - "BSK_3C_Proliferation_down"
  - "BSK_3C_SRB_down"
  - "BSK_3C_Vis_down"
  - "BSK_4H_Eotaxin3_down"
  - "BSK_CASM3C_Proliferation_down"
  - "BSK_LPS_VCAM1_down"
  - "BSK_SAg_CD38_down"
  - "BSK_SAg_CD40_down"
  - "BSK_SAg_Proliferation_down"
  - "BSK_hDFCGF_CollagenIII_down"
  - "BSK_hDFCGF_Proliferation_down"
  - "CEETOX_H295R_11DCORT_dn"
  - "CEETOX_H295R_ANDR_dn"
  - "TOX21_ARE_BLA_agonist_ratio"
  - "TOX21_TR_LUC_GH3_Antagonist"